### ISSUE TITLE
As a developer, I want a `sso-react` package to add to my express/react application

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-template-app#28]
This is the client-side part of #25

###### select client-side components to be extracted to package - all using the Button component library https://github.com/button-inc/service-development-toolkit

To package - as React components using the toolkit:
-    session-timeout modal
-    session-refresher component that registers to user events

To document - provide examples with the toolkit (no implementation needed)
-    login button
-    logout button
-    register button

**Comment by pbastia** [comment]
Back to the backlog - the logic needs redesign:
- SessionRefresher cannot extend the session without notifying the SessionTimeoutHandler - and SessionTimeoutHandler cannot just query the remaining time without extending the session - or we'll indefinitely refresh the session without any user action
- This needs to be either packaged up under one component that handles both session extension and time tracking, or with a clever arrangement of callback and notification between both components.

**Comment by LindsayMacfarlane** [comment]
Nothing for me to test on this one :)
