### ISSUE TITLE
System architecture review

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-template-app#65]
#### Description
As Clean Growth digital services expands and becomes more complex, we have an opportunity to review our system architecture so that we can better plan for future development and enhancements.

#### Checklist
- [x] Review current system architecture
- [x] Review current state of devops tooling (versions of airflow, shipit, metabase...)

#### Deliverables
- [x] "next steps" list - a blue-sky thinking of the path forward (supporting an output-based pricing system). What key steps would we need to take?
- [ ] drafting an implementation plan for the aforementioned steps
- [ ] list of reusable components that could be packaged up and maintained as separate libraries / npm packages

**Comment by LindsayMacfarlane** [comment]
@pbastia @matthieu-foucault  - I've created this ticket to capture the system architecture review. Please take a look and update the checklist.

**Comment by matthieu-foucault** [comment]
Are there specific attributes of the architecture that we want to review here? See https://en.wikipedia.org/wiki/List_of_system_quality_attributes for a example list of attributes.

I see this issue is in the `cas-template-app` repo. Do we want to do a review encompassing all our deployed products and their associated devops tooling?

**Comment by LindsayMacfarlane** [comment]
Thank you so much team! 

Confirming - did the last two bullets under deliverables get completed or do we need follow up tickets to address?

**Comment by pbastia** [comment]
"drafting an implementation plan for the aforementioned steps": consensus is that we don't have enough concrete information or requirements to come up with an implementation plan. We do have some pieces of software and architecture plans that will be documented in a separate document

"list of reusable components that could be packaged up and maintained as separate libraries / npm packages": again, the 'could' is key and this work should be undertaken only if there is a need. Most pieces of the application can be refactored to be generic and reused if needed :)
