### ISSUE TITLE
sso-express: allow `authorizationUrlParams` to be configured per request

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-template-app#67]
`authorizationUrlParams` is currently configured for the entire middleware. This does not allow the application to change the  `authorizationUrlParams` on a per-request basis. This use case is present in applications that have multiple identity providers, and where we want to have multiple login buttons and change the `kc_idp_hint` based on which button was clicked.

## Feature proposal

- Change the type of  `authorizationUrlParams` from `{[key: string]: string}` to `Record<string,string> | (req: Request) => Record<string,string>`
- Handle the case where authorizationUrlParams is a function in `loginController`

**Comment by pbastia** [comment]
implemented in #68
