### ISSUE TITLE
DevOps: Enable automatic exposure response of SA keys on GCP

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-template-app#79]
GCP is introducing a new protection service in case a service account key is leaked/compromised
It would be a good idea to enable it early

> What do you need to do?
You have the ability to [modify this behavior](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnotifications.google.com%2Fg%2Fp%2FANiao5qdA05TVgSCOvew3RA1rKqhV5CytshneTs3XJGhCjmsQzVXauNSRNbfgU35BP02H9OqOcLalN8MdKKnPngKof7QEN6kLSIzq3qV7LIHa2YoxDP3oWEN5zNgewSdJ-PNPUH2JLPoe8cYKpnNOyCg15N2PVyUBBvjyjEnpfV-FlPlc38xdgbjzVtIulKO8820vAmqCKUk9R0JI0h7GwubXyTmK9b9s7npq6YtVaxbiKv6cQCpyhpoFrGTSopjKjIyT-s0en_6u3gM-vR9xO_Uoa35E4OgScxkeBvCbgRXsHZvHDye--xM0FTAE27JL1UziQ&data=05%7C02%7Channa.vovk%40gov.bc.ca%7Ca78837943e4d4416372008dc476e67f5%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C638463786714889674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=RMCPIA89Au542v3tZ2uzE8zmmcCnLsXrbE1cJ5oD3GA%3D&reserved=0) ahead of time by taking one of the following actions:
> 1. Opt-in early by setting the IAM.serviceAccountKeyExposureResponse constraint to DISABLE_KEY which will enable the protection immediately.
> 1. Opt-out anytime by setting the IAM.serviceAccountKeyExposureResponse constraint to WAIT_FOR_ABUSE which will disable the protection.
> 1. Do nothing, in which case Google will enable the protection on your behalf on June 16, 2024.

Resources:
- https://cloud.google.com/resource-manager/docs/organization-policy/restricting-service-accounts#disable-exposed-keys

**Comment by pbastia** [comment]
@patriciarussellCAS I think this needs one of us to explore how to allow organization policies to be managed - I'm not sure why I wasn't able to edit that. I'd say let's not worry about it and wait for June 16 for GCP to enable it automatically.

**Comment by dleard** [comment]
@pbastia closing this as June 16 has passed
